# This set of services can be used to bring up a bam-studio cms engine and database locally
version: '3'
services:
  engine:
    image: ruby:2.3.8
    command: 'bash -c "(bundle check || bundle install) && bundle exec rails server -p 3000"'
    ports:
      - "3000:3000"
    volumes:
      - ./engine:/app
      - /app/tmp/pids # Required or else we get conflicting server.pid's
      - /app/log
      - engine-bundle:/bundle
    working_dir: /app
    environment:
      - BUNDLE_PATH=/bundle
      - RAILS_ENV=development
      - S3_KEY_ID=mock-s3-key-id
      - S3_SECRET_KEY=mock-s3-secret-key
      - S3_BUCKET=bam-studio-mock
      - S3_BUCKET_REGION=us-east-1
      - MONGODB_URI=mongodb://db:27017/bam-studio
  wagon:
    image: ruby:2.3.8
    command: 'bash -c "(bundle check || bundle install) && bundle exec wagon serve"'
    ports:
      - 3333:3333
    volumes:
      - ./wagon:/app
      - /app/tmp/pids # Required or else we get conflicting server.pid's
      - /app/log
      - wagon-bundle:/bundle
    working_dir: /app
    environment:
      - BUNDLE_PATH=/bundle
  db:
    image: mongo:2.6.12
    volumes:
      - datadb:/data/db
volumes:
  engine-bundle:
  wagon-bundle:
  datadb:
