source 'https://rubygems.org'

ruby '2.1.3'

gem 'rails', '3.2.21'
gem 'railties'
gem 'locomotive_cms',    '~> 2.5.6', :require => 'locomotive/engine'
gem 'thin', :group => 'production'
gem 'unicorn'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',    '~> 3.2.3'
  gem 'coffee-rails',  '~> 3.2.1'
  gem 'uglifier',      '>= 1.0.3'
  gem 'compass',       '~> 0.12.7'
  gem 'compass-rails', '~> 2.0.0'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby
end



# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
