development:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
  options:
    identity_map_enabled: true
test:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
  options:
    identity_map_enabled: true